name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ github.token }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_and_deploy_hugo:
    name: Build and Deploy Hugo based static site to Wasmer Edge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Wasmer
        uses: wasmerio/setup-wasmer@v2
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.119.0"
      - name: Build Hugo
        run: hugo --minify
      - name: Deploy app to Wasmer Edge
        run: wasmer deploy --token=${{ secrets.WASMER_CIUSER_PROD_TOKEN }} --publish-package --non-interactive --no-wait --no-persist-id
